//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class t_user_info
{
    public string UserId { get; set; }
    public string PuserId { get; set; }
    public string LoginName { get; set; }
    public Nullable<int> UserType { get; set; }
    public string IMSI { get; set; }
    public string BindMsisdn { get; set; }
    public string Password { get; set; }
    public Nullable<int> ErrorTimes { get; set; }
    public Nullable<System.DateTime> LockTime { get; set; }
    public string NickName { get; set; }
    public string Email { get; set; }
    public string HeadImage { get; set; }
    public string Sex { get; set; }
    public string Birthday { get; set; }
    public string Constellation { get; set; }
    public string Work { get; set; }
    public string Introduce { get; set; }
    public string Favorite { get; set; }
    public string ProvinceId { get; set; }
    public string CityId { get; set; }
    public string Address { get; set; }
    public Nullable<System.DateTime> RegTime { get; set; }
    public string RegPlace { get; set; }
    public Nullable<System.DateTime> LastLogonTime { get; set; }
    public string LastLogonPlace { get; set; }
    public Nullable<System.DateTime> LudTime { get; set; }
    public string LudPlace { get; set; }
    public string WwwFirLogonCId { get; set; }
    public Nullable<System.DateTime> WwwFirLogonTime { get; set; }
    public string WwwDeviceId { get; set; }
    public string MoFirLogonCId { get; set; }
    public Nullable<System.DateTime> MoFirLogonTime { get; set; }
    public string MoDeviceId { get; set; }
    public string WapFirLogonCId { get; set; }
    public Nullable<System.DateTime> WapFirLogonTime { get; set; }
    public string WapDeviceId { get; set; }
    public string PayPassword { get; set; }
    public Nullable<int> PayPasswordStatus { get; set; }
    public Nullable<int> PaySwitchStatus { get; set; }
    public string PartitionID { get; set; }
    public Nullable<int> BlogStat139 { get; set; }
    public string BlogUID139 { get; set; }
    public string Follow_ap { get; set; }
    public string FetionNo { get; set; }
    public Nullable<int> fetionType { get; set; }
    public string personalSign { get; set; }
    public Nullable<int> privacySet { get; set; }
}
