//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspirecn.Entities.Cssp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CsspEntitiesContainer : DbContext
    {
        public CsspEntitiesContainer()
            : base("name=CsspEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ServiceAccessReqEntity> ServiceAccessReqEntities { get; set; }
        public DbSet<ParamNameEntity> ParamNameEntities { get; set; }
        public DbSet<ServiceAccessRespEntity> ServiceAccessRespEntities { get; set; }
    }
}
