//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspirecn.Entities.Cssp
{
    using System;
    
    public partial class RequestType
    {
        public RequestType()
        {
            this.Params = new ParamsType();
        }
    
        public string SPID { get; set; }
        public string SPServiceID { get; set; }
        public string ChannelID { get; set; }
        public string ContentID { get; set; }
        public string MSISDN { get; set; }
        public string FeeMSISDN { get; set; }
    
        public ParamsType Params { get; set; }
    }
}
