//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspirecn.Entities.Cssp
{
    using System;
    
    public partial class ResponseType
    {
        public string RetCode { get; set; }
        public string SPID { get; set; }
        public string SPServiceID { get; set; }
        public string Price { get; set; }
        public string OrderID { get; set; }
        public string PushID { get; set; }
    }
}
